"""document status, tenant scoping, cascade

Revision ID: 224ba7553324
Revises: bb7ae9478211
Create Date: 2026-07-31 23:52:14.442412

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "224ba7553324"
down_revision: str | Sequence[str] | None = "bb7ae9478211"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # add nullable, backfill from the owning KB, then tighten to NOT NULL —
    # so this migration is safe on databases that already hold documents
    op.add_column("documents", sa.Column("tenant_id", sa.Uuid(), nullable=True))
    op.execute(
        "UPDATE documents SET tenant_id = kb.tenant_id "
        "FROM knowledge_bases kb WHERE documents.kb_id = kb.id"
    )
    op.alter_column("documents", "tenant_id", nullable=False)
    op.add_column(
        "documents",
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PARSING",
                "CHUNKED",
                "EMBEDDING",
                "READY",
                "FAILED",
                name="documentstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
            server_default="PENDING",
        ),
    )
    op.add_column("documents", sa.Column("error_message", sa.String(length=2000), nullable=True))
    op.create_index(op.f("ix_documents_tenant_id"), "documents", ["tenant_id"], unique=False)
    op.drop_constraint(op.f("fk_documents_kb_id_knowledge_bases"), "documents", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_documents_kb_id_knowledge_bases"),
        "documents",
        "knowledge_bases",
        ["kb_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        op.f("fk_documents_tenant_id_tenants"), "documents", "tenants", ["tenant_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_documents_tenant_id_tenants"), "documents", type_="foreignkey")
    op.drop_constraint(op.f("fk_documents_kb_id_knowledge_bases"), "documents", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_documents_kb_id_knowledge_bases"),
        "documents",
        "knowledge_bases",
        ["kb_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_documents_tenant_id"), table_name="documents")
    op.drop_column("documents", "error_message")
    op.drop_column("documents", "status")
    op.drop_column("documents", "tenant_id")
    # ### end Alembic commands ###
